import type { PredictionResponse } from '../../types'
import { formatINR } from '../../utils/format'

interface PredictionResultProps {
  result: PredictionResponse
}

export default function PredictionResult({ result }: PredictionResultProps) {
  return (
    <div className="card overflow-hidden">
      <div className="border-b border-slate-200 bg-brand-50 px-6 py-5">
        <p className="text-xs font-medium uppercase tracking-wide text-brand-700">
          Estimated Fare
        </p>
        <p className="mt-1 text-3xl font-bold tracking-tight text-brand-900 sm:text-4xl">
          {formatINR(result.predicted_price)}
        </p>
        <p className="mt-1 text-xs text-brand-600">
          Currency: {result.currency}
        </p>
      </div>

      <div className="space-y-4 px-6 py-5">
        <div className="flex items-start gap-2.5 rounded-lg border border-amber-200 bg-amber-50 p-3">
          <span aria-hidden="true">ℹ️</span>
          <p className="text-xs leading-relaxed text-amber-800">
            ML-based estimate — actual fares may vary. Prediction generated by
            the <strong>FareSight</strong> model (HistGradientBoosting
            Regressor) served through the FastAPI backend.
          </p>
        </div>

        <div>
          <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">
            How this works
          </h3>
          <ol className="mt-2 list-inside list-decimal space-y-1.5 text-sm text-slate-600">
            <li>Your flight details are sent to <code className="rounded bg-slate-100 px-1">POST /api/predict</code>.</li>
            <li>The backend derives the same engineered features used during training.</li>
            <li>The trained regression model returns an estimated fare.</li>
          </ol>
        </div>

        <div>
          <h3 className="text-xs font-semibold uppercase tracking-wide text-slate-500">
            What affects the estimate
          </h3>
          <p className="mt-2 text-sm leading-relaxed text-slate-600">
            Model feature importance shows <strong>Duration</strong> and{' '}
            <strong>Distance</strong> dominate, followed by travel class and
            days before departure. Those inputs have the biggest influence on
            the price you see here.
          </p>
        </div>
      </div>
    </div>
  )
}
